### ISSUE TITLE
"厦门" convert to 'shamen'

### ISSUE THREAD

**Issue by yanyingwang** [Xuhao/china_region_data#4]
Hello, guys, 

when use pypinyin.lazy_pinyin or pypinyin.pinyin, it transform '厦门' to 'shamen', but the right output is 'xiamen'

reference: https://github.com/mozillazg/python-pinyin/issues/59

**Comment by Xuhao** [comment]
Thanks for the report.

**Comment by yanyingwang** [comment]
just for note here, that ‘沈阳' is not correct also.

**Comment by Xuhao** [comment]
@yanyingwang  correct in 6a11d7e, thanks a lot!
